 head = delete (head, 90);
    print(head);
    head = delete (head, 5);
    print(head);
    head = delete (head, 90);
    print(head);
    head = delete (head, 120);
    print(head);
    head = delete (head, 1000);
    print(head);
    head = delete (head, 9000);
    print(head);
    head = delete (head, 100);
    print(head);
    head = delete (head, 10);
    print(head);
    head = delete (head, 20);
    print(head);
    head = delete (head, 30);
    print(head);
    head = delete (head, 40);
    print(head);
    head = delete (head, 50);
    print(head);
    head = delete (head, 60);
    print(head);
    head = delete (head, 70);
    print(head);
    head = delete (head, 80);
    print(head);